name: GitPilot Log Collector

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  log-and-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (read-only)
        uses: actions/checkout@v3

      - name: Set timezone
        run: sudo timedatectl set-timezone America/New_York

      - name: Run conquest log script
        run: |
          chmod +x scripts/create_conquest_log.sh
          ./scripts/create_conquest_log.sh

      - name: Run lead gen log script
        run: |
          chmod +x scripts/create_leadgen_log.sh
          ./scripts/create_leadgen_log.sh

      - name: Upload log artifacts
        uses: actions/upload-artifact@v3
        with:
          name: marketing-logs
          path: |
            conquested-ads/
            leadgen-ads/
