name: GitPilot Artifact-Only Log Capture

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  archive-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Timezone
        run: sudo timedatectl set-timezone America/New_York

      - name: Run Conquest Log Script
        run: |
          chmod +x scripts/create_conquest_log.sh
          ./scripts/create_conquest_log.sh

      - name: Run Lead Gen Log Script
        run: |
          chmod +x scripts/create_leadgen_log.sh
          ./scripts/create_leadgen_log.sh

      - name: Archive Conquested Ads
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: conquested-ads
          path: conquested-ads/

      - name: Archive Lead Gen Ads
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: leadgen-ads
          path: leadgen-ads/
